### ISSUE TITLE
Broken links for certificate chain and revoked certificates

### ISSUE THREAD

**Issue by pcrocker-pivotal** [pivotal-cf/archived-code-signing-public#1]
I'm trying to use the `pkgverify` program to verify a download from Pivnet.  The application fails with:
```
$ pkgverify -artifact cf-1.8.12-build.1.pivotal -signature cf-1.8.12-build.1.pivotal.sig
No chain file or URL specified; defaulting to https://raw.githubusercontent.com/pivotal-cf/code-signing-certificates/master/chain.pem
No list of revoked certificates specified; defaulting to https://raw.githubusercontent.com/pivotal-cf/code-signing-certificates/master/revoked.json
error GETing URL: status code 404
```
These are the same URLs listed on the `customer.md` page and give `404: Not Found` errors.

**Comment by rosenhouse** [comment]
It appears that the certs repo (like this one) was renamed, so links got broken.  It now lives at https://github.com/pivotal-cf/archived-code-signing-certificates

You may try setting `PKG_TOOLS_OVERRIDE_CA_URL` as described in the README.

However, I believe this tool is no longer supported.  I'm not even sure if the CA here is the same one that's still signing PivNet artifacts.  @johnpfield may know more about the current status.

**Comment by pcrocker-pivotal** [comment]
Pivnet is referencing these as the verification instructions for the Elastic Runtime (see attached).  If this tool is no longer supported/updated Pivnet should be updated accordingly.

**Comment by crawsible** [comment]
Hey @pcrocker-pivotal, Pivnet PM here.

Thanks for surfacing this error; we'll update the signature checking instructions. We are *just* starting to sign build artifacts now, so there are still some issues with the process. I'll update you hopefully sometime tomorrow (11/2) with up-to-date instructions.

**Comment by crawsible** [comment]
Hi @pcrocker-pivotal, sorry for the delay. You can follow the instructions [here](https://github.com/pivotal-cf/code-signing-cli) to check the code signature against the 1.8.12 binary. Use one of the binaries marked as "production".

Let me know if you have any further questions.

**Comment by rosenhouse** [comment]
@crawsible : I don't have access to that repo.  Is it meant to be public?

**Comment by crawsible** [comment]
@rosenhouse No, it's not. I'm not sure how widely it's meant to be viewable by Pivots yet, but we're actively discussing how best to distribute it to customers.
